// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Wj5t0hakH7JBWT48OfEeDY7h9rupZpQ',
    appId: '1:378871858515:web:4f2b5620b76d17f4cc4da6',
    messagingSenderId: '378871858515',
    projectId: 'blublu-fb773',
    authDomain: 'blublu-fb773.firebaseapp.com',
    storageBucket: 'blublu-fb773.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5DEXjZB2bsWwd_Cjdt_Ig-0GnaIc9tE',
    appId: '1:378871858515:android:cca9e2317335467acc4da6',
    messagingSenderId: '378871858515',
    projectId: 'blublu-fb773',
    storageBucket: 'blublu-fb773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDFdlXzoeO2dbeKT5w544Xd-ZKj4MiI2w',
    appId: '1:378871858515:ios:fa1e860feea4c5bbcc4da6',
    messagingSenderId: '378871858515',
    projectId: 'blublu-fb773',
    storageBucket: 'blublu-fb773.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlublu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDFdlXzoeO2dbeKT5w544Xd-ZKj4MiI2w',
    appId: '1:378871858515:ios:fa1e860feea4c5bbcc4da6',
    messagingSenderId: '378871858515',
    projectId: 'blublu-fb773',
    storageBucket: 'blublu-fb773.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlublu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Wj5t0hakH7JBWT48OfEeDY7h9rupZpQ',
    appId: '1:378871858515:web:6cdf9c665c6b0e14cc4da6',
    messagingSenderId: '378871858515',
    projectId: 'blublu-fb773',
    authDomain: 'blublu-fb773.firebaseapp.com',
    storageBucket: 'blublu-fb773.firebasestorage.app',
  );
}
